### ISSUE TITLE
Add images to products in marketplace

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#11]
# 📘 Issue Description
- Currently, the cards for the products on the marketplace page don't provide any visual for the product, we want to include a way to visualize some pictures of it.

## ✅ Acceptance Criteria
- The cards now have a set of images of the product.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the Product interface to include an 'images' property. Modified the ProductList component to display the first image of each product. Added a placeholder image if no images are available.

You can review changes in this commit: https://github.com/lattaai13/KaizeNodeLabs-SafeSwap-11/commit/66c703e3d76a6944c542d947fc28c03d713288e7.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by thiagoulloa** [comment]
Can I work on this?

**Comment by abdegenius** [comment]
@danielcdz can i assist with this?

**Comment by Jimmy-csc** [comment]
Hello @danielcdz, can I be assigned this issue

**Comment by jaykayudo** [comment]
can i be assigned this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by derianrddev** [comment]
My Background and How It Can Be Leveraged
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to contribute and support the development of this project.

How I Plan on Tackling This Issue
I will include a section within each card to display product images.
I will ensure each card has a set of images associated with the product.
I will verify that the images display correctly in the cards.

**Comment by josephchimebuka** [comment]
Can I take this from here?

**Comment by Supa-mega** [comment]
Is it okay if I take this?

**Comment by Unickhub** [comment]
Could I take on this issue?

**Comment by Naomi-Gift** [comment]
Could I take on this issue?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript, would love to work on this , my ETA is >8 Hours and ill create a draft PR in 5 hours time. Thank you for this opportunity. :)

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Frontend  stark net project and more  .   please /assign  this issue .
Thank You

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. can i please address this task

**Comment by LeonM95** [comment]
Hello,

My name is Leo, and I'm a junior software developer from Costa Rica. This will be my first Hackathon, and I am excited to apply for this issue.

I have experience working with C#, JavaScript, Node.js, some TypeScript, CSS and HTML. I believe this issue will be a fantastic opportunity to enhance my coding/design skills.

Currently, I am also learning about Web3 technologies.

Thank you for considering my application.

Best regards,  
Leo

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

i will ask for visual of the product to insert in the empty card by adding the images to the asset folder if their is one and if there is not, I will add it 

Thanks
