### ISSUE TITLE
Add return to home button in Marketplace page

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#12]
# 📘 Issue Description
- We want to have a way to return to the landing page from the marketplace page.

## ✅ Acceptance Criteria
- A button is in the header of the marketplace page that returns the user to the landing page.

**Comment by thiagoulloa** [comment]
Can I work on this as my fist contibution? @danielcdz 
I'm a fullstack developer with experience in Web3 projects

**Comment by NueloSE** [comment]
@danielcdz kindly assign me the above task I have experience in using nextjs.

A psuedo approach to solve the above task :

- I would implement my change in [market place header](https://github.com/KaizeNodeLabs/SafeSwap/blob/main/frontend/app/marketplace/page.tsx) file.
- I'll import the useRouter from Next.js and add a Home icon from our existing Lucide icons library.
- For the layout, I think placing the home button next to the sidebar toggle makes the most sense. I'll create a flex container on the left side of the header to group these two buttons together nicely.
- To handle the navigation, I'll use Next.js's router to send users back to the landing page ('/'). This keeps our navigation consistent with the rest of the app.

kindly assign 

ETA <= 24hours

**Comment by Jemiiah** [comment]
Hello I'm a frontend developer in web3 I have contributed in previous OD Hacks  i have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :

**Comment by KodeSage** [comment]
Could I take on this issue?


My background and how it can be leveraged 

I'm a Software Engineer with over 4+ years of  demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development and Solidity, and Cairo/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust and external Projects like Passage, Stellar, etc. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements. With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

 I'm excited to bring this experience and drive for innovation to your team.


Implementation Plan:

Design:
Add a visually consistent button labeled "Home" or "Landing Page" in the marketplace page header.
Style the button to match the existing UI design guidelines for seamless integration.
Functionality:
The button will be linked to the route of the landing page.
Ensure accessibility by adding proper ARIA labels for screen readers.
Implementation Plan:
Update Header Component:
Add a conditional render to include the button only on the marketplace page.
Routing Logic:
Ensure the button uses the correct route to redirect users to the landing page


Timeline
I estimate completing this implementation within 20-30 minutes, including coding and styling,

**Comment by NueloSE** [comment]
@danielcdz kindly assign me the above task I have experience in using nextjs.

A psuedo approach to solve the above task :

I would implement my change in [market place header](https://github.com/KaizeNodeLabs/SafeSwap/blob/main/frontend/app/marketplace/page.tsx) file.
I'll import the useRouter from Next.js and add a Home icon from our existing Lucide icons library.
For the layout, I think placing the home button next to the sidebar toggle makes the most sense. I'll create a flex container on the left side of the header to group these two buttons together nicely.
To handle the navigation, I'll use Next.js's router to send users back to the landing page ('/'). This keeps our navigation consistent with the rest of the app.
kindly assign

ETA <= 24hours

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by rogeralbp** [comment]
Would like to introduce my web development skills in this open source project by running the app and make live buttons implementations to check the most accurate

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by derianrddev** [comment]
My Background and How It Can Be Leveraged
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to contribute and support the development of this project.

How I Plan on Tackling This Issue
I will add a button to the header of the marketplace page that redirects the user to the landing page.
I will ensure the button displays correctly.

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by josephchimebuka** [comment]
Can I try solving this issue?

**Comment by Unickhub** [comment]
Can I handle this task?

**Comment by Unickhub** [comment]
Can I handle this task?

**Comment by Supa-mega** [comment]
Can I attempt this issue?

**Comment by zintarh** [comment]
Could I grab this task?

**Comment by Steph3097** [comment]
Hey! I’m Sttef and i have experience in front-end development, I own experience working with tools like figma and zeplin 

I’m part of the Dojo Team ⛩️

I would be happy to help and to be part of this one! I will create the button, ensure it matches the design perfectly and make sure that it has the desired behavior I will follow the steps mentioned to deliver what is needed! 

Thank you!

**Comment by Naomi-Gift** [comment]
May I take care of this?

**Comment by GideonBature** [comment]
Can I handle this task?

My name is Gideon Bature, a Software Engineer with experience using TypeScript. If assigned this issue, I should be able to send my first PR within 12 hrs. 

Thank you!

**Comment by Bran18** [comment]
Hello there. I’m Brandon, part of the ⛩️ Dojo Coding community, and I would love to contribute to this project! 🚀  This might be my first contribution here.

I've done a couple of these feats for our apps and I would love to help out with this one for you. I believe it can be done with hooks following the latest standards and also check if there's something else that might be improved around it. 

Lmk if I can start working on it.  Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18. 

BTW tks for taking the time mate 🙏

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript, would love to work on this , my ETA is >2 Hours and ill create a draft PR in 1 hour time. Thank you for this opportunity. :)

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

My approach to solve this issue :

Will start by making a button on the marketplace page.
And then adding a route assigned to that button that when user clicks on the button it should take user to the home page or the landing page probably the route will be /home.
And will run it locally so that its persistent and do not get any sort of bug and it everything is alright will make a pr.

ETA-2days

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by Unickhub** [comment]
Can I contribute to this one?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by 0xDeon** [comment]
Could I take over this issue?

I’ll add a button in the header of the marketplace page that routes the users back to the Homepage page when clicked.
ETA: 24 hours.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Frontend stark net project and more  .   please /assign  this issue .
Thank You 
ETA : 1- hours

**Comment by MullerTheScientist** [comment]
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript. i'd love to address this task

**Comment by DiegoB1911** [comment]
I am a Full Stack Developer with two years of experience, primarily working with Next.js. Currently, I am a member of Dojo Coding, where I am learning Cairo and Web3 technologies.

To solve this issue, I would:

1. Add the Button: Place a "Return to Home" button in the header of the marketplace page.

2. Set Up Navigation: Use Next.js Link to navigate the user to the home page when the button is clicked.

3. Style the Button: Ensure the button matches the page's design

4. Test: Verify the button works correctly

**Comment by LeonM95** [comment]
Hello,

My name is Leo, and I'm a junior software developer from Costa Rica. This will be my first Hackathon, and I am excited to apply for this issue.

I have experience working with C#, JavaScript, Node.js, some TypeScript, CSS and HTML. I believe this issue will be a fantastic opportunity to enhance my coding/design skills.

Currently, I am also learning about Web3 technologies.

Thank you for considering my application.

Best regards,  
Leo
