### ISSUE TITLE
Add chat with seller button in the products cards

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#15]
# 📘 Issue Description
**Add a "Chat with Seller" Button (Design Only)**

We want to introduce a button on the product page to allow users to start a chat with the seller. At this stage, the task focuses solely on the design aspect, with no functionality required.

**Task Details:**
- Design a visually appealing and intuitive "Chat with Seller" button.
- Ensure the button aligns with the overall marketplace style and theme.
- The button should be responsive and accessible for all users.

**Notes:**
- The focus is purely on the design; no backend or frontend logic needs to be implemented at this point.
- Include the design in the appropriate section of the product page.

Feel free to explore creative options for the button while maintaining consistency with the existing UI!

**Comment by EmeteZ** [comment]
Hello, can I work on this? @danielcdz
I have experience with UI/UX design.

**Comment by 0xdevcollins** [comment]
Could I take over this issue?

**Comment by khayss** [comment]
May I be assigned to this?

## Background and Relevant Experience

I’ve designed clean, responsive UI elements like buttons for various web platforms. My focus is on usability and visual appeal.

## Plan for Tackling the Issue

- Design a "Chat with Seller" button for the product page.
- Ensure it aligns with the marketplace style and is responsive.
- Focus on button design without backend functionality.

**Comment by Steph3097** [comment]
Hey! I’m Sttef and i have experience in front-end development, I own experience working with tools like figma and zeplin 

I’m part of the Dojo Team ⛩️

I would be happy to help and to be part of this one! I will create the button and ensure it matches the design perfectly! I will follow the steps mentioned to deliver what is needed! 

Thank you!

**Comment by NueloSE** [comment]
Could I take over this issue?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
Could I take on this issue?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Supa-mega** [comment]
Can I be assigned to this?

**Comment by Unickhub** [comment]
Could I try solving this?

**Comment by Jemiiah** [comment]
Step 1: Understand Design Context
I will analyze the existing UI/UX of the marketplace to understand the color palette, typography, button styles, and spacing conventions.
By examining the landing page and marketplace page layout, I’ll determine where the "Chat with Seller" button can be positioned effectively.

Step 2: Sketch the Button Design
I'll create a button design that matches the marketplace's style:
Shape: Rounded edges for a modern, approachable feel.
Icons: Optionally include a chat icon (e.g., speech bubble) for better intuitiveness.
Text: Use clear and concise text like "Chat with Seller".
Colors: Use primary or accent colors from the marketplace theme while maintaining readability and contrast.
Hover Effects: Add subtle effects like color changes or shadowing to make it interactive.

Step 3: Placement on Product Cards
I’ll position the button in a logical area on the product cards, such as:
Below the product details (e.g., name, price).
Near the "Buy Now" or "Add to Cart" buttons for logical flow.
The placement will respect spacing and avoid cluttering the card layout.

Step 4: Responsiveness and Accessibility
Responsiveness: Ensure the button adapts to various screen sizes:
Small screens: Center the button below product details.
Large screens: Align it to match the layout flow of product cards.
Accessibility: Add considerations for visually impaired users:
High contrast between text and background.
Focus states for keyboard navigation.

Step 5: Create the Design
Using tools like Figma or Adobe XD:
I’ll replicate the existing product card and add the new button design.
Ensure consistency in fonts, margins, and button styles.
Share a design mockup or prototype for review.

**Comment by Steph3097** [comment]
Hey! I’m Sttef and i have experience in front-end development, I own experience working with tools like figma and zeplin 

I’m part of the Dojo Team ⛩️

I would be happy to help and to be part of this one! I will create the button and ensure it matches the design perfectly! I will follow the steps mentioned to deliver what is needed! 

Thank you!

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript, would love to work on this , my ETA is >48 Hours and ill create a draft PR in 17 hours time. Thank you for this opportunity. :)

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by LeonM95** [comment]
Can I attempt this issue?
