### ISSUE TITLE
Change tab name to SafeSwap

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#17]
# 📘 Issue Description
**Update Browser Tab Placeholder to "SafeSwap"**

When running the project locally, the browser tab currently displays a placeholder text. Update this placeholder to display **"SafeSwap"** for better branding and clarity.

**Task Details:**
1. Locate the configuration or HTML file where the placeholder for the browser tab is set (e.g., `<title>` tag in the `index.html` or equivalent file).
2. Replace the current placeholder text with **"SafeSwap"**.
3. Verify that the change reflects correctly when running the project locally.

**Comment by thiagoulloa** [comment]
Can I work on this? @danielcdz 
I'm a fullstack developer with experience in Web3 projects

**Comment by petersdt** [comment]
![Screenshot from 2024-11-20 15-43-54](https://github.com/user-attachments/assets/0dcb316c-859e-4e99-956f-6dfa815f72a5)

@danielcdz kindly assign 

attached is a screenshot of the implementation 

ETA <= 5mins

**Comment by jaykayudo** [comment]
@danielcdz can i work on this?

**Comment by Steph3097** [comment]
Hello! i’m From Costa Rica and i have over 5 years of experience in front-end. 

I’m part of the Dojo team ⛩️

I’m really interested on contribute to this issue, i will find the HTML title tag and replace it with the one you preferred! 

Thank you!

**Comment by Steph3097** [comment]
Hello! i’m From Costa Rica and i have over 5 years of experience in front-end. 

I’m part of the Dojo team ⛩️

I’m really interested on contribute to this issue, i will find the HTML title tag and replace it with the one you preferred! 

Thank you!

**Comment by Steph3097** [comment]
Hello! i’m From Costa Rica and i have over 5 years of experience in front-end. 

I’m part of the Dojo team ⛩️

I’m really interested on contribute to this issue, i will find the HTML title tag and replace it with the one you preferred! 

Thank you!

**Comment by Steph3097** [comment]
Hello! i’m From Costa Rica and i have over 5 years of experience in front-end. 

I’m part of the Dojo team ⛩️

I’m really interested on contribute to this issue, i will find the HTML title tag and replace it with the one you preferred! 

Thank you!

**Comment by khayss** [comment]
Mind if I take this issue?

## Background and Relevant Experience

I specialize in frontend development using TypeScript and Next.js, with experience designing modals and forms. I’m skilled at creating intuitive and responsive user interfaces, ensuring a seamless experience for users.

## Plan for Tackling the Issue

- Add a "Upload Product" button in a prominent location.
- Design a modal with placeholders for product details: name, description, price, category, and image upload.
- Ensure responsive styling to match the marketplace’s theme.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
Could I take over this issue?I can comfortably handle this issues

**Comment by derianrddev** [comment]
My Background and How It Can Be Leveraged  
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to contribute and support the development of this project.

How I Plan on Tackling This Issue
I will locate the layout file where the metadata object is defined.
I will change the title value to "SafeSwap" and adjust the description to improve the brand image and SEO of the application.
I will run the project locally to ensure the updated title appears correctly in the browser tab.

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Unickhub** [comment]
Could I grab this task?

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Unickhub** [comment]
Could I grab this task?

**Comment by zintarh** [comment]
Can I take care of this issue?

**Comment by Unickhub** [comment]
Mind if I try this one?

**Comment by SudiptaPaul-31** [comment]
Can I get this issue?

My approach: 

Will start by locating the title tag and will replace with the name as provided.
Will run it to check whether its running properly

**Comment by Steph3097** [comment]
Hello! i’m From Costa Rica and i have over 5 years of experience in front-end. 

I’m part of the Dojo team ⛩️

I’m really interested on contribute to this issue, i will find the HTML title tag and replace it with the one you preferred! 

Thank you!

**Comment by GideonBature** [comment]
Can I contribute to this one?

May I take this issue on?

My name is Gideon Bature, a Software Engineer with experience using TypeScript. If assigned this issue, I should be able to send my first PR within 12 hrs. 

Thank you!

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in typescript would love to work on this , my ETA is >20 Hours and ill create a draft PR in 10 hours time. Thank you for this opportunity. :)

**Comment by ShantelPeters** [comment]
I’d like to help with this.

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Frontend  stark net project and more  .   please /assign  this issue .
Thank You 
ETA : 1 hours

**Comment by LeonM95** [comment]
Hello,

My name is Leo, and I'm a junior software developer from Costa Rica. This will be my first Hackathon, and I am excited to apply for this issue.

I have experience working with C#, JavaScript, Node.js, some TypeScript, CSS and HTML I believe this issue will be a fantastic opportunity to enhance my coding skills.

Currently, I am also learning about Web3 technologies.

Thank you for considering my application.

Best regards,  
Leo

**Comment by khayss** [comment]
Thanks for assigning the issue to me. I'll make the PR for it ASAP.
