### ISSUE TITLE
Create a MD template for the PRs descriptions

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#3]
## Summary
- Create a markdown file that holds a template with required and important details to fill in when proposing a PR
- Feel free to propose a template
- This template should be just a guide don't add to much text with the headers is ok

**Comment by Oshioke-Salaki** [comment]
Please can I Do this?
I have previous experience in writing documentation and i have maintained a project before on onlydust so i know the best template for PR descriptions. And i would love to contribute to this stellar project. please give me the chance. I won't let you down ser.

This is my onlydust profile. ETA of 2 hours
https://app.onlydust.com/u/Oshioke-Salaki

@danielcdz

**Comment by 0xdevcollins** [comment]
Would love to tackle this!

**Comment by PabloVillaplana** [comment]
Let me help me with this issue Homie

Is it okay if I take this? ☝️

**Comment by Gerson2102** [comment]
### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

# Proposed Solution for Issue

I would resolve this issue in the following way:

1. **Create a PR Template File**: Start by creating a Markdown file named `PULL_REQUEST_TEMPLATE.md` in the `.github` directory to standardize PR descriptions.

2. **Define Key Sections**: Structure the template with headers that guide contributors to provide necessary information without adding excessive text. Here is a sample structure for the template:

   ```markdown
   # Pull Request Description

   ## Summary
   _Provide a concise description of the changes included in this pull request._

   ## Related Issue
   _Link the related issue by adding `#<issue number>`._

   ## Type of Change
   - [ ] Bug fix
   - [ ] New feature
   - [ ] Documentation update
   - [ ] Other (describe below)

   ## Proposed Changes
   _List the main changes introduced by this PR._
   
   ## Screenshots or GIFs (if applicable)
   _Attach screenshots or GIFs to help understand the visual impact of changes._

   ## Additional Context
   _Include any additional information that could be useful for reviewers._
   ```

3. **Minimal Guidance**: Since the requester asked for a minimalistic approach, avoid adding instructions within each section beyond the headers. The headers themselves should be enough to prompt the required information.

4. **Commit and Push**: After creating the `PULL_REQUEST_TEMPLATE.md` file, commit and push it to the repository. This will automatically load the template in the PR descriptions, ensuring consistent and complete information in future pull requests.

**Comment by diegoTech14** [comment]
Hello, I'm Diego a software engineer from Costa Rica and member of Dojo Coding ⛩️ I've created some documentation for projects like KaizenNodeLabs, ByteBeasts and Dipdup, I would love to contribute to this issue



#### I have some experience documenting projects and my step by step to solve it looks like this:

1. I will search and design a great PR template
2. I will propose the design template
3. Create a template according to the requirements


Kind regards,

Diego Duarte Fernández

**Comment by Benjtalkshow** [comment]
I’m interested in this one.

**Comment by gadyrcdz** [comment]
Is it okay if I tackle this? I'm part of the Dojo Coding Community

**Comment by lauchaves** [comment]
Hey Im Lau Chaves Id would like to contribute to this one! I have already helped other mainteners created issues and would love to do the md file for this project! 

Please check some issues template on these links: 

https://github.com/keep-starknet-strange/joyboy/issues/249
https://github.com/keep-starknet-strange/joyboy/issues/232
....

**Comment by 0xBinayak** [comment]
# Pull Request Title

## Description


## Related Issue(s)


## Changes Summary
- [ ] Feature 1
- [ ] Feature 2
- [ ] Refactoring/bug fixes
- [ ] Documentation updates

## Type of Changes
- [ ] Bug fix
- [ ] New feature
- [ ] Enhancement
- [ ] Documentation

## Checklist
- [ ] Code follows project conventions
- [ ] Tests written and passing
- [ ] Documentation updated where applicable
- [ ] Linked to an open issue
- [ ] Ready for review

## Screenshots (if applicable)


## Additional Notes



example template

**Comment by rogeralbp** [comment]
Hola , me gustaria trabajar en este issue, tengo template de MD de mi experiencia documentando conociento para la organizacion, soy miembo del dojo, seria mi primer colaboracion

**Comment by omsant02** [comment]
I’d like to work on this.

**Comment by KevinLatino** [comment]
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I won the Base LATAM's Buildathon. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

This is an example of how i will make the template:

- Pull Request Title.  
- Description: Briefly explain the changes made.  
- Related Issue: Link to the associated issue.  
- Changes Made: List key modifications.  

and more, also  I would review PR templates from more established projects to identify best practices and common elements

but i can make some changes or add features if you want to!
