### ISSUE TITLE
Add SafeSwap to landing page

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#31]
# 📘 Issue Description
**Enhance the Landing Page with SafeSwap Branding**

The current landing page lacks any visual identity or branding for SafeSwap. To establish a strong brand presence, we want to incorporate the "SafeSwap" title prominently on the page. Since we don’t yet have a logo, feel free to experiment with different font styles and placements.

**Task Details:**
1. Propose 2-3 design options where the "SafeSwap" title is effectively integrated into the landing page.
   - **Option 1**: Place the title prominently in the header/navigation bar for consistent visibility.
   - **Option 2**: Feature the title as a central hero element on the page, paired with a tagline or key message.
   - **Option 3**: Include the title in the footer or as a watermark-like element for subtle branding.

2. Experiment with different font types and sizes to explore distinct styles that align with SafeSwap's vision.

3. Present mockups or design sketches for each option to aid in decision-making.

**Notes:**
- Ensure the title is visually appealing and blends seamlessly with the current landing page design.
- Focus on creating a strong and professional look that resonates with users.
- Keep the designs responsive and adaptable to various screen sizes.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue? @danielcdz

**Comment by khayss** [comment]
Pls assign this to me

**Comment by anonfedora** [comment]
Hi, I'm Eleazar, a fullstack Blockchain developer (proficient in Nextjs, Reactsjs, Cairo, Nestjs), looking for my first contribution to this project...

**Comment by danielcdz** [comment]
@0xdevcollins any updates?

**Comment by 0xdevcollins** [comment]
@danielcdz I will make a PR soon ser

**Comment by SudiptaPaul-31** [comment]
@danielcdz Can I start working on this issue
