### ISSUE TITLE
Improve card description in Landing Page

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#32]
## Overview
![image](https://github.com/user-attachments/assets/442d8083-7b98-4cc9-8544-2e5a39939d8f)

The landing page includes a section highlighting the features provided by the marketplace. To enhance clarity and showcase transparency, we want to update the escrow-related section with additional information.

## Tasks
- Add a Reference to [Trustless Work API](https://www.trustlesswork.com/)
- Update the escrow-related section to explicitly mention the use of the Trustless Work API for managing smart contracts.
- Highlight its role in enabling trustless and secure transactions.
- Improve the Description:
   - Refine the current content to clearly explain the benefits of using the Trustless Work API within the marketplace ecosystem.
- Include a Link to Their Website:
   - Add a clickable link to the Trustless Work API's official website for users to learn more about the service.

**Comment by Iwueseiter** [comment]
Hi @danielcdz can I work on this? 
I'm a frontend and smart contract developer. I look forward to contributing to this project.

To improve the landing page, I will look at the existing design and add section which will  reference the Trustless work API. 
I will ensure it is working as expected to prevent inconsistencies and ensure it is responsive on all device.

**Comment by Jemiiah** [comment]
@danielcdz i’ma frontend developer can I work on this issue

**Comment by ikemHood** [comment]
Hey @danielcdz Can I get this done,

EDT: 24hrs

I pay attention to aesthetics.

**Comment by KevinMomanyi** [comment]
May I handle this issue?

**Comment by mimisavage** [comment]
I can handle this task , kindly assign please

**Comment by Benjtalkshow** [comment]
Hello @danielcdz 
Can this be my first task in the project? I want to work on this issue.

**Comment by Michaelkingsdev** [comment]
I'd love to work on this.

**Comment by caxtonacollins** [comment]
I am applying through the onlydust platform.
Can I take this issue? please assign me. this will be my first time contributing

**Comment by ooochoche** [comment]
GM, I can improve the required task if this issue is assigned to me.

**Comment by danielcdz** [comment]
@Iwueseiter any updates?

**Comment by Iwueseiter** [comment]
> @Iwueseiter any updates?

I will create a PR before close of work today.

**Comment by SudiptaPaul-31** [comment]
@danielcdz Can I jump on this issue?

**Comment by Iwueseiter** [comment]
I'm creating a PR Now please.
