### ISSUE TITLE
Init project with NextJS

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#4]
## Summary
- We want to handle the frontend of the project using NextJS
- Init the frontend using NextJS
  - We need a point to start so following this [guide](https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup) should be good
- Add somewhere a Markdown file with the instructions on how to run the frontend
- Paste all the frontend files and stuff in a new `/frontend` directory in the root of the project

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue @danielcdz

**Comment by 0xdevcollins** [comment]
Let me handle this issue!

**Comment by Jemiiah** [comment]
Hello @danielcdz I would love to contribute to this issue

**Comment by deeseeker** [comment]
I'm a Frontend developer with 2 years of experience in React, JS and TS. I recently contributed to Starknet React and Starknet Quest projects, demonstrating my ability and command of my skillset. I am very comfortable with next JS and I can take on this challenge.

Permit me to push a PR for this task

**Comment by JosueBrenes** [comment]
Hi, I'm Josué Brenes and I'll be working on issue.
I'm Dojo Coding member. ⛩️

I estimate this will take 1 day to complete.

# Proposed Solution for Issue

I would resolve this issue in the following way:

1. **Set Up the Frontend Using NextJS**:
   - Initialize a new Next.js application in the `/frontend` directory by running the following commands:
     ```bash
     npx create-next-app@latest frontend
     cd frontend
     ```
   - Follow the setup prompts or use the default configurations provided by Next.js.

2. **Add Setup Guide in a Markdown File**:
   - Create a Markdown file in the `/frontend` directory named `README.md`. This file will contain instructions on how to run and develop the frontend.
   - Example content for the `README.md` file could be:
     ```markdown
     # Frontend Setup and Development

     ## Running the Development Server
     To start the development server, run:
     ```bash
     npm run dev
     ```
     The app will be available at `http://localhost:3000`.

     ## Building for Production
     To create a production build, run:
     ```bash
     npm run build
     ```

     ## Starting the Production Server
     To run the production server after building, use:
     ```bash
     npm start
     ```

3. **Organize Frontend Files**:
   - Place all the frontend files and folders within the newly created `/frontend` directory, ensuring separation between frontend and backend code.

4. **Commit and Push**:
   - After setting up and organizing the frontend, commit the changes to the repository to maintain a clear separation of project components.

**Comment by Benjtalkshow** [comment]
Can I take this issue?

**Comment by derianrddev** [comment]
Hello, I am Derian, a software engineer focused on fullstack web development, and I am currently part of Dojo Coding. I have experience with backend technologies like Cairo, C#, Python, and Node.js, as well as frontend development using React and JavaScript/TypeScript. I don’t have experience with NextJS yet, but I would like to learn.

How I would resolve the issue:

- I will understand the problem that needs to be solved by carefully reading the issue description.
- I will use all resources provided in the problem to better understand the task.
- If I have any questions, I will ask them as soon as possible in Telegram.
- I will open a PR and wait for your feedback.
- I will make the necessary changes based on the PR review.

**Comment by brolag** [comment]
Hi Daniel, 

I have experience working with front end technologies. I recenlty set up the project for https://github.com/Vagabonds-Labs/cofiblocks and I have some ideas that could work.

My plan is:
- Create a boilerplate project using next.js, tailwindcss, any componentes library of your preference, biome for linting and git hooks for keeping the project clean.
- Also I can add a PRD document that could work as a prompt for Cursor or any AI Driven Development workflow.

Thanks in advance.

**Comment by Villarley** [comment]
Hey! I’d love to jump in and get the frontend started for this project. I have a solid background in Next.js, and I’m excited to make my first contribution here. Looking forward to bringing my Next.js experience to the team and making a meaningful impact on the project! Feel free to reach out on my social media if you have any questions.

**Comment by KevinLatino** [comment]
Hi @danielcdz

I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I won the Base LATAM's Buildathon. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

To solve this issue, here’s what I’d do:

To solve this issue, I’d create a /frontend folder in the root and initialize a Next.js project in it. Then, I’d add a README.md inside /frontend with instructions: go to /frontend, install dependencies, run the dev server, and open http://localhost:3000. This would set up the frontend and provide a quick start guide.

**Comment by rogeralbp** [comment]
Estoy aprendiendo next.js, me gustaria poner mi conocimiento a prueba para ayudarles a crecer juntos, seria mi primera contribucion en el codigo abierto

**Comment by omsant02** [comment]
i would like to take this issue
