### ISSUE TITLE
Update README and PULL REQUEST TEMPLATE 

### ISSUE THREAD

**Issue by derianrddev** [KaizeNodeLabs/SafeSwap#42]
# 📘 Issue Description
The *Installation* section of the README is incorrect, and it seems that a section is missing in the PR template to request screenshots or videos to aid in the review.

## 🔍 Steps to Reproduce
1. Review the *Installation* section of the README.
2. Notice that the instructions are incorrect.
3. Check recent PRs and observe the absence of images or videos in the descriptions.

## ✅ Acceptance Criteria
- Correct the *Installation* section in the README.
- Add a section in the PR template requesting screenshots or videos to aid in the review.

## 🌎 References
- 

## 📜 Additional Notes
-

**Comment by Iwueseiter** [comment]
Hi @derianrddev can I quickly work on this?
