### ISSUE TITLE
Fill guidelines from Issues

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#44]
## Description  

The Git, Issues, and Contribution guidelines are written as pinned issues in the project’s **Issues** tab. While this is helpful, we want to organize these guidelines into dedicated files within the repository for better accessibility and structure.  

---

## ✅ Steps to Complete  

1. **Extract Content:**  
   - Review the pinned issues in the **Issues** section to gather the relevant content for each guideline.  

2. **Fill the Files:**  
   - Create a new  `docs/` directory in the repository, and move the already created md files from the root of the repo.
   - Populate each file with the corresponding content from the pinned issues.

**Comment by Benjtalkshow** [comment]
@danielcdz 
Can i work on this task. its my first time contributing to this amazing project. Thanks

**Comment by Michaelkingsdev** [comment]
I'd like to handle this task. I applied via onlydust and i am a new contributor.

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by aguilar1x** [comment]
I'd love to work on this!
