### ISSUE TITLE
Make Trustless Work link clickable in Smart Contract Escrow section

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#49]
## 📘 **Description**

In the **Smart Contract Escrow** section on the landing page, the "Trustless Work" link is currently just plain text and not clickable. The link should redirect users to the Trustless Work page when clicked.

## 🔢 **Steps**

1. Locate the component rendering the **Smart Contract Escrow** section on the landing page.
2. Modify the code to wrap the "Trustless Work" text in an `<a>` tag. Use the correct `href` value to link to the **Trustless Work** page.
3. Set the link to open in a new tab by adding the attribute `target="_blank"`.
4. Apply consistent styling to the link, ensuring it matches the design shown in the attached image.

## ✅ **Acceptance Criteria**

- "Trustless Work" is a clickable link.
- The link redirects users to the **Trustless Work** page.
- The link opens in a new tab.
- The link styling is visually consistent with the rest of the site's design, as per the attached image.

## 🌎 **References**

![image (10)](https://github.com/user-attachments/assets/1d7c3641-fa5e-4be5-897d-2ff875890f36)

## 📜 **Additional Notes**

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by mimisavage** [comment]
May I try my hand at this?

**Comment by Supa-mega** [comment]
Let me try this one!

**Comment by josephchimebuka** [comment]
Can I work on this, please?

**Comment by abdegenius** [comment]
Could I take over this issue?

**Comment by ShantelPeters** [comment]
I’d like to resolve this.

**Comment by danielcdz** [comment]
@Supa-mega any updates?
