### ISSUE TITLE
Refactor ProductList Logic into Separate Component

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#51]
## 📘 Description

The logic for `ProductList` needs to be refactored into a reusable component to improve maintainability and structure. The products should be moved into a separate file for better data management, and a dedicated folder for type definitions should be created to ensure consistency across the application.

## 🔢 **Steps**

1. Move the `ProductList` logic (currently in the Marketplace page) to a new file named `product-list.tsx` inside the `components/marketplace` directory.
2. Create the `components/marketplace` folder if it doesn’t already exist.
3. Move all products data to a new file named `placeholder-data.ts` inside the `lib` directory.
4. Create a new folder named `types` inside the `app` directory and add a file `index.ts`.
5. Copy the `Product` interface into `types/index.ts`.
6. Update all relevant imports to use the refactored component, product data, and type definitions.
7. Validate that the application functions as expected after the changes.

## ✅ Acceptance Criteria

- The `ProductList` logic should be fully refactored into a reusable component.
- Product data should be organized in the `placeholder-data.ts` file.
- Type definitions should be centralized in `types/index.ts`.
- The application should function correctly after the changes.

## 🌎 References

Not applicable.

## 📜 Additional Notes

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by RajeshRk18** [comment]
Can I take up this issue? I have experience working on various typescript(and some react) projects. I will follow all the steps and make a valid PR.

**Comment by BigBen-7** [comment]
Code Refactoring is my stuff, can i jump on this?

**Comment by mimisavage** [comment]
Is this issue still available?

**Comment by Supa-mega** [comment]
Can I jump on this task?

**Comment by khayss** [comment]
I'd be happy to do this.

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by Kingsuite** [comment]
Let me try this one!

**Comment by OWK50GA** [comment]
Could I take on this issue?

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by abdegenius** [comment]
May I handle this issue?

**Comment by GideonBature** [comment]
May I be assigned to this?

**Comment by therealemino** [comment]
May I be assigned to this?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by RajeshRk18** [comment]
Can I take up this issue? I have experience working on typescript projects. I will follow all the steps and make sure that ProductList is reusable and move product data to separate file.

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

How I will tackle this issue?

1. To tackle this issue, I’ll refactor the ProductList logic into a reusable component inside components/marketplace/product-list.tsx, move product data to lib/placeholder-data.ts, and centralize type definitions in app/types/index.ts.
2.  I’ll ensure all related imports are updated, and the application functions seamlessly after these changes.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.


How will I tackle this task?

1. My approach involves reorganizing the ProductList logic into a separate component located in components/marketplace/product-list.tsx.
2.  Product data will be moved to lib/placeholder-data.ts, and type definitions will be centralized in app/types/index.ts to enhance maintainability and consistency. Let me know if you need more details!

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by portableDD** [comment]
Hi, i am Emmanuel Dorcas, and i will like to tackle this issues
I am software developer in React js and Typescript, I have three years experinece
my estimated time is 2days

how I will tackle this:
I will Move the ProductList logic to a new file named product-list.tsx
I will Create the components/marketplace folder if it doesn’t already exist.
i will Move all products data to a file named placeholder-data.ts inside the lib directory.
i will create the Product interface  inside a file called index,ts in types folder
I will update all relevant imports to use the refactored component, product data, and type definitions.
i will makes sure to confirm that the application functions are working accordingly

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I will  start by creating a new product-list.tsx file inside a components/marketplace directory and move the relevant logic from the Marketplace page into this file, ensuring it is reusable by accepting props like products. Next, create a placeholder-data.ts file in a lib directory to store and export the product data separately. Then, centralize type definitions by creating a types folder in the app directory with an index.ts file, where the Product interface will be defined and exported. Update all relevant imports in the application to use the new component, data file, and type definitions, and validate that the application works correctly after these changes.

**Comment by mariocodecr** [comment]
@danielcdz thanks hommie
