### ISSUE TITLE
Add Breadcrumb Navigation to Marketplace

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#52]
## 📘 Description

Users are currently struggling to navigate the marketplace due to the lack of clear navigation that indicates their current location. Adding a breadcrumb navigation will enhance the user experience by providing a simple way to return to previous pages or navigate back to the landing page. Additionally, aligning the breadcrumb navigation with the "Add Product" button will help maintain a visually cohesive and organized layout.

## 🔢 **Steps**

1. Create a new file named `breadcrumb-navigation.tsx` inside the `components/ui` directory.
2. Name the component `BreadcrumbNavigation`.
3. Implement the navigation using the shadcn/ui breadcrumb component.
4. Configure the "Home" breadcrumb to redirect users to the landing page.
5. Align the breadcrumbs with the "Add Product" button.
6. Ensure the navigation is responsive and functional.

## ✅ Acceptance Criteria

- Breadcrumb navigation must be correctly implemented and functional.
- The "Home" breadcrumb must redirect to the landing page.
- Breadcrumbs must be aligned with the "Add Product" button.
- The design must be responsive and consistent across all devices.

## 🌎 References

- [shadcn/ui breadcrumb](https://ui.shadcn.com/docs/components/breadcrumb)
- [Lucide Icons](https://lucide.dev/icons/)

![image](https://github.com/user-attachments/assets/255b4731-1ba7-4132-876f-a227d1136810)

## 📜 Additional Notes

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by Shoetan** [comment]
I'd be happy to do this.

I am Emmanuel returning contributor skilled in React,Tailwind CSS, TypeScript, Cairo and Redux, with experience contributing to open-source projects on only dust
 Recently contributed to Carbonable PR: https://github.com/Carbonable/contracts-watcher/pull/27   I’ll address this issue by delivering clean, efficient, and well-documented code.  Onlydust Profile: https://app.onlydust.com/u/Shoetan

**Comment by mimisavage** [comment]
May I be assigned to this?

**Comment by josephchimebuka** [comment]
Can I handle this task?

**Comment by Supa-mega** [comment]
Can I tackle this one?

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, Id love to give a hand on this one!

I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 

for this one Id add the breadcrumb component and implementation, Id make sure it works as expected and matches the design

**Comment by khayss** [comment]
I'd like to take this issue.

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by abdegenius** [comment]
Can I work on this, please?

**Comment by Ekene001** [comment]
I'm Ekene, a frontend and blockchain developer with proficiency in typescript, React/Next js, Solidity and Rust. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

here's How i'll tackle this task:

I will implement a breadcrumb navigation system to make it easier for users to track their location within the marketplace and navigate back to previous pages effortlessly. I will ensure the breadcrumbs are clearly visible and align them with the "Add Product" button to maintain a clean and cohesive design. Once implemented, I will test the functionality and layout to ensure it improves the user experience without disrupting the overall visual balance.

ETA: 2days

**Comment by ONEONUORA** [comment]
I’d like to resolve this. I am a full stack and blockchain developer. ETA 24 hours

**Comment by Emmanex01** [comment]
Can I work on this, please?

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

1. To tackle this issue, I’ll create a BreadcrumbNavigation component in components/ui/breadcrumb-navigation.tsx using the shadcn/ui breadcrumb system.
2.  The "Home" breadcrumb will redirect to the landing page, and the breadcrumbs will be aligned with the "Add Product" button to ensure visual consistency and responsiveness.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.


How will I tackle this task?

1. I’ll implement a BreadcrumbNavigation component in components/ui/breadcrumb-navigation.tsx, leveraging the shadcn/ui breadcrumbs. 
2. The "Home" link will redirect to the landing page, and I’ll align the navigation with the "Add Product" button to maintain a cohesive layout across devices.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, Typescript, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. 

I will create the `breadcrumb-navigation.tsx` file in `components/ui` and define the `BreadcrumbNavigation` component. I will implement the `shadcn/ui` breadcrumb, configuring "Home" to redirect to the landing page. I will align the breadcrumbs with "Add Product" and make them responsive.
