### ISSUE TITLE
Integrate Footer into Global Layout

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#53]
## 📘 Description

Currently, the footer is visible only on the landing page, which creates inconsistencies in the application’s design. To ensure a consistent user experience, the `Footer` component should also appear on the Marketplace page by integrating it into the global layout.

## 🔢 **Steps**

1. Add the `Footer` component into the global layout file of the application.
2. Remove the `Footer` import from the landing page.
3. Validate that the `Footer` displays correctly on the Marketplace page without affecting the existing layout or functionality.

### ✅ Acceptance Criteria

- The `Footer` should appear on all pages.
- Page functionality and design should remain unaffected after the implementation.

### 🌎 References

Not applicable.

### 📜 Additional Notes

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by Ibinola** [comment]
Hello @danielcdz 

## Background and Relevant Experience

I'm a frontend developer with experience using React, Next.js and TypeScript and I'm also skilled at creating intuitive and responsive user interfaces, ensuring a seamless experience for users.

Relevant experience contributing to open-source projects where I used the technologies mentioned above ([Pear AI](https://github.com/trypear/pear-landing-page/pulls?q=author%3AIbinola) and [SpotNet](https://github.com/djeck1432/spotnet/pull/235)).  

Let me try this one!

## Plan for Tackling the Issue
* Move the `Footer` component to the global layout of the application
* Remove the `Footer` import from the landing page
* Ensure the `Footer` component displays properly across all pages(market place) page w/o affecting any existing layout

**Comment by BigBen-7** [comment]
This would be nice for my first issue, can it be assigned to me?

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by Supa-mega** [comment]
I’m interested in this one.

**Comment by Kingsuite** [comment]
Can I take this from here?

**Comment by khayss** [comment]
Can I be assigned to this?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by zintarh** [comment]
May I be assigned to this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by abdegenius** [comment]
I'd like to take this issue.

**Comment by therealemino** [comment]
Hi, I've gone through the repository and I believe I'll be able to handle this.

**Comment by austineblaise** [comment]
I will integrate the Footer into the global layout, remove it from the landing page, and ensure it displays correctly on the Marketplace page without affecting the existing design or functionality.

**Comment by 7-falseparfait** [comment]
I’d like to work on this.

**Comment by Naomi-Gift** [comment]
Could I take a shot at this?

**Comment by ShantelPeters** [comment]
I’m interested in this one.

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by akintola4** [comment]
Can I try solving this issue?

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by making the footer to appear on all  the pages on the website and ensure that it is not affecting the layout of the "Marketplace Page". ETA 2 days

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by portableDD** [comment]
Hi, i am Emmanuel Dorcas, i will like to tackle ths issues.

I'm a frontend developer with experience using React, Next.js and TypeScript and I'm also skilled at creating intuitive and responsive user interfaces, ensuring a seamless experience for users.

how i will tackle this issues:

Add the Footer component into the global layout file of the application.
Remove the Footer import from the landing page.
make sure the Footer displays correctly on all pages (including the marketplace)without affecting the existing layout or functionality and check for responsiveness.

i will tackle this in 2 days.

Thanks
