### ISSUE TITLE
Refactor Header Component for Application-wide Use

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#54]
## 📘 Description

The Header currently differs between the Landing page and the Marketplace page. To ensure consistency and reusability across the application, both headers need to be unified into a single, reusable component. The unified header will include the logo, search bar, wallet connection button, and dark mode toggle button while removing unnecessary elements.

## 🔢 Steps

1. Move the current `HeaderComponent` (located on the Marketplace page) to a new file named `header.tsx` inside the `components/ui` directory.
2. Rename the component to `Header`.
3. Remove the hamburger menu and replace it with the logo.
4. Remove the Home button and all related logic.
5. Move the existing dark mode toggle button into the header.

## ✅ Acceptance Criteria

- The unified header should be used across the entire application, including both the landing page and the marketplace.
- The header should include the logo, search bar, wallet connection button, and dark mode toggle button.
- The header must be responsive, ensuring it adapts well to different screen sizes.

## 🌎 References

Not applicable.

## 📜 Additional Notes

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by Ayoazeez26** [comment]
I plan on handling this by creating a new file named header.tsx inside the components/ui directory and moving the current HeaderComponent into it, then rename the component to Header.
I will remove the hamburger menu and replace it with the logo and also remove the home button and all related logic. I will then move the existing dark mode toggle button into the header as instructed.
Before creating a PR, I would ensure the header component is used application wide, including the landing page and marketplace. I will make sure it is fully responsive on all screen sizes and make sure it includes the logo, search bar, wallet connection button, and lastly the dark mode toggle button.
ETA - 1 day.

**Comment by Ibinola** [comment]
Can I contribute to this one?

Background and Relevant Experience

I'm a frontend developer with experience using React, Next.js and TypeScript and I'm also skilled at creating intuitive and responsive user interfaces, ensuring a seamless experience for users.

Relevant experience contributing to open-source projects where I used the technologies mentioned above ([Pear AI](https://github.com/trypear/pear-landing-page/pulls?q=author%3AIbinola) and [SpotNet](https://github.com/djeck1432/spotnet/pull/235)).  

Plan for Tackling the Issue
1. Move the current `HeaderComponent` a new file
2. Replace the hamburger menu with the actual logo and also remove the Home button and all it's related logic.
3. Move the dark mode toggle button into the header.  ETA: 4-6hours

**Comment by armandocodecr** [comment]
### **Issue Submission: Unifying the Header Component for Consistency Across the Application**

**Hi Daniel,**

I’m eager to contribute to enhancing the consistency and reusability of the application’s interface. After reviewing the issue description, I propose the following approach to unify the Header component across the Landing page and the Marketplace. My solution focuses on maintaining a clean design, responsiveness, and future scalability.

### **Proposed Solution**

**1. File and Component Refactor**

•	**New Location:**

Move the current HeaderComponent from the Marketplace page to components/ui/header.tsx. This centralizes the header component in the ui directory for easy reusability across different pages.

•	**Component Renaming:**

Rename the component to Header to ensure clarity and align with naming conventions.

**2. Header Simplification**

•	**Logo Integration:**

Replace the existing hamburger menu with the logo to streamline navigation and align with the desired design.

•	**Remove Home Button:**

Eliminate the Home button and all related logic to simplify the header and avoid redundancy.

•	**Dark Mode Toggle:**

Integrate the existing dark mode toggle button directly into the header for better accessibility and design coherence.

**3. Responsive Design**

•	Ensure the header adapts seamlessly to various screen sizes using TailwindCSS. The layout will prioritize accessibility and usability on both desktop and mobile devices.

**4. Header Features**

The unified Header component will include:

•	**Logo** for brand identity.

•	**Search Bar** for enhanced navigation.

•	**Wallet Connection Button** for seamless user interaction with wallet features.

•	**Dark Mode Toggle Button** for theme flexibility.

### **Why This Approach?**

1.	**Consistency:**

A single, reusable Header component promotes design consistency and reduces duplication across the Landing page and Marketplace.

2.	**Maintainability:**

Centralizing the component makes future updates easier and ensures changes propagate across the entire application seamlessly.

3.	**Scalability:**

The clean and modular structure allows for future enhancements without compromising the current design.

4.	**Experience:**

My experience in refactoring UI components and ensuring responsive design guarantees a polished and reliable solution.

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by BigBen-7** [comment]
Can i solve this?
My Plan:
 Move the HeaderComponent to a new file, replace the hamburger menu with the logo, remove the Home button and its logic, and add the dark mode toggle to the header. ETA: 4-6 hours.

**Comment by Supa-mega** [comment]
Could I grab this task?

**Comment by Steph3097** [comment]
Hello @danielcdz! Im Sttef!
Im part of Dojo Coding and I am excited to contribute to this task. I have over five years of experience in front-end development and extensive expertise in creating modular and maintainable components.
To address this issue, I propose the following approach:
-Move the current HeaderComponent from the Marketplace page to a new file named header.tsx within the components/ui directory, following the prescribed project structure.
-Rename the component to Header 
-Remove the hamburger menu and replace it with the logo for a cleaner design.
-Remove the Home button and all related logic.
- Relocate the dark mode toggle button into the header 
- Verify the updated Header component works as expected on both the Landing and Marketplace pages, ensuring consistency and functionality in different screen sizes.
Thank you for considering my application. I look forward to contributing my skills to this project!

**Comment by khayss** [comment]
Would love to tackle this!

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by OWK50GA** [comment]
Let me try this one!
Hi, I'm Wilfrid Okorie, a Frontend Web Developer with experience in Next.js and React.js, and I'd like to take this issue.

Expect my first PR within 24 hours

**Comment by abdegenius** [comment]
Can I tackle this one?

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by fabrobles92** [comment]
Hello Fab here,

I am a member of dojo coding, I work as a full stack where I have had experience working with several js frameworks like Plain React, Next and Vue. 

I would love to tackle this issue and make my first contrib to this project  by moving the Header to its own file and then replacing/moving the elements described in the instructions.

**Comment by RajeshRk18** [comment]
Can I take up this issue? I have experience working on react components. I will follow all the steps and make sure that Header is resuable across the application.

**Comment by ShantelPeters** [comment]
I’d like to help with this.

**Comment by Levi-Ojukwu** [comment]
Can I attempt this issue?

**Comment by Levi-Ojukwu** [comment]
## About Me 
Hello @danielcdz, I am Levi.
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## Tackling This Issue
- To tackle this issue, first I will move the `HeaderComponent` to a new file named `header.tsx` that is located inside the `components/ui`directory and rename the components to `Hearder`.
- Then I will remove the  hamburger menu and replace it with the logo.
- Afer that I will remove the home button and all its related logics or comditions.
- Then I will remove the dark mode toggle button to the header of the page.

If assigned this issue, I will ensure compliance with the team and follow the team's guideline.

## ETA - 8 - 10 hours max

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

To tackle this issue, I will refactor the Header component into components/ui/header.tsx to unify the headers across the application. The component will include the logo, search bar, wallet connection button, and dark mode toggle button while ensuring responsiveness and removing unnecessary elements like the hamburger menu and Home button.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

How will I tackle this task?

1. I plan to consolidate the Header into a reusable component under components/ui/header.tsx. 
2. The refactored header will feature the logo, search bar, wallet connection, and dark mode toggle, eliminating redundant elements and maintaining responsiveness across all pages.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by RareMmemshima** [comment]
I'd love to work on this!
I'm a frontend and smart contract developer. I have a solid background with react, tailwind, nextjs, javascript, typescript, cairo ETC.  
I will implement this task as expected. 
I'm new to onlydust and i look forward to contributing to this project.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world with +40 open source contributions so far.

### How would I approach this issue?
For this header unification task I would start by taking a look to the current components (landing and marketplace) to identify common elements, and which elements to keep from each of the implementations.
Then I'll start migrating the Marketplace header component to a new common ui component file. Once that is ready I'll continue with the component renaming, removal of unneeded components and integrating missing components such as the dark mode toggle.
After that, I'll perform a quick testing to make sure any of the subcomponents are broken and that the header keeps its responsiveness.
