### ISSUE TITLE
Replace Carousel with Single Image in Product Cards

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#55]
## 📘 Description

The current product cards use an image carousel, which can impact page loading times when there are many products and images. To improve performance and simplify the design, replace the carousel with a single static image for each card. Ensure the design remains visually appealing and responsive.

## 🔢 Steps

1. Replace the image carousel in the product card component with a single static image.
2. Verify that the updated design aligns well with the existing layout.
3. Ensure the new product card design is responsive across different screen sizes.

## ✅ Acceptance Criteria

- The new product card design should use a single static image for each card.
- The design should remain visually appealing and align with the existing layout.
- The product card should be responsive and adapt correctly to different screen sizes.

## 🌎 References

Not applicable.

## 📜 Additional Notes

- Consider choosing the first image of each product as the static image.

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by jaykayudo** [comment]
Can i work on this as soon as ODHack11 starts?

**Comment by BigBen-7** [comment]
Can i take this?

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchttps://mattedsgn.com/himebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ Can I contribute to this one?

**Comment by khayss** [comment]
Can I attempt this issue?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by abdegenius** [comment]
May I be assigned to this?

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by Naomi-Gift** [comment]
Could I grab this task?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by ShantelPeters** [comment]
I’d love to work on this task.

**Comment by austineblaise** [comment]
I'm a frontend JavaScript/TypeScript Blockchain developer. I'll replace the product card carousel with a single static image to improve load times while keeping the design appealing and responsive. Looking forward to the task!
