### ISSUE TITLE
Create Product Page

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#56]
## 📘 Description

The current modal for displaying product details may limit user experience when handling extensive product information. While modals are effective for concise data, they can become cluttered and difficult to navigate when showing comprehensive details. To address this, a dedicated product page is desired.

## 🔢 Steps

1. Create a new folder called `product` inside the `app` directory.
2. Create a new page in the `product` folder to display static details for a single product.
3. Ensure the design is visually appealing and responsive across different screen sizes.

## ✅ Acceptance Criteria

- The product page should include the same details as the current modal but exclude the close button.
- It should be visually appealing and consistent with the rest of the application.
- The layout should be responsive.

## 🌎 References

Not applicable.

## 📜 Additional Notes

- The product page will initially display static information without dynamic product selection.

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by sonkiee** [comment]
id love to take this

**Comment by danielcdz** [comment]
@sonkeydotcom ODHack hasn't started, please wait

**Comment by BigBen-7** [comment]
i'd love to work on this!

**Comment by 0xdevcollins** [comment]
I'd be happy to do this.

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by Supa-mega** [comment]
Can I try solving this issue?

**Comment by khayss** [comment]
May I take care of this?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Steph3097** [comment]
Hello @danielcdz! Im Sttef
I am excited to contribute on this issue. I’m Part of Dojo Coding team and I have experience in front-end development, I specialize in building responsive, intuitive, and visually engaging interfaces. 
To address this issue, I propose the following approach:
- Create a new product folder inside the app directory
- Develop a new page within the product folder to display details of the product. 
- Ensure the page is fully responsive in all screen sizes.
Looking forward to contribute in this project! thank you!

**Comment by AdejareSamad** [comment]
Hi @danielcdz , I'd love to work on this design.

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, Typescript, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.

I have worked on many pages similar to this one, so I am familiar with the topic. My approach is as follows: first, I will go to the specified path, create the folder mentioned in the issue, and build the page according to the style and design aligned with the other elements of the project. I will ensure it is responsive and well-designed.

ET: 2-3 days

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by OWK50GA** [comment]
I’d like to work on this.
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

I have experience with Next.js, and since the modal already exists, all I need to do is make it into a page and make it visually appealing, then remove the specifics for a modal such as the close button. 

I will submit my first PR within 24 hours 

Expect my first PR within

**Comment by 0xDeon** [comment]
Could I be assigned to this?

I'll start to tackle this issue creating a folder named product inside the app directory, setting up a new route in the product folder. I plan to create the modal content into a full page view that's super clean and matches the app design to the last details while also focusing on making the layout easy to navigate and intuitive

ETA: 48 Hrs

**Comment by abdegenius** [comment]
I’d like to work on this.

**Comment by austineblaise** [comment]
**How I Can Solve the Issue**

As a frontend/JavaScript/blockchain developer, I will create a new product page by setting up a folder and page for displaying static product details. I’ll ensure the design is visually appealing, consistent with the app, and responsive across all screen sizes. The page will include the product information from the current modal, excluding the close button.

**Comment by JoelVR17** [comment]
### Request to Work on Product Page Creation Issue  

Hello, team!  

I would like to take on the task of creating the new product page as described. This involves transitioning the current modal-based product detail view into a dedicated page to enhance user experience when handling extensive product information.  

#### Plan of Action:  
- **Folder and File Setup**:  
  - Create a new `product` folder inside the `app` directory.  
  - Add a new page to display static details for a single product.  

- **Content and Design**:  
  - Include all current product details from the modal, excluding the close button.  
  - Ensure the page is visually appealing and maintains consistency with the rest of the application.  

- **Responsive Layout**:  
  - Test and optimize the layout for responsiveness across multiple screen sizes.  

#### Acceptance Criteria:  
- The product page includes the same information as the current modal.  
- The design is visually appealing and consistent.  
- The layout is fully responsive.  

If approved, I’ll ensure compliance with the team’s guidelines and submit a clear and detailed pull request. Please let me know if there are any additional considerations for this task.  

Thank you!  
**Joel Vargas**

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by AdejareSamad** [comment]
I'd love to work on this!

**Comment by coxmars** [comment]
I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

1- I will review the project structure to place the code and other parts as expected.
2- I’m going to use the code structure/best practices implemented among the project codebase to continue the standard
3- I will implement the product page following the mentioned guidelines.
5- Finally, I’ll test all changes to validate all is working as expected.

ET: 3 days

**Comment by ONEONUORA** [comment]
I'd love to give this a go. I am a full stack and blockchain developer. ETA 24 hours

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Luluameh** [comment]
Could I take a shot at this?

**Comment by akintewe** [comment]
Hi i am oluwasola, I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript. I’ve made over 14 contributions to over 9 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 12 hours.

**Comment by Levi-Ojukwu** [comment]
## About Me 
Hello @danielcdz! I am Levi
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM-compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## Tackling this issue
- To tackle this issue, first I will create a directory called `product` inside the app directory.
- Then I will create a page inside the product folder i created, and this will display the static details for single products 
- I will ensure the page is user-friendly and responsive on all screen sizes (devices), using best code practice and naming convention.

If assigned to me , I’ll ensure compliance with the team and follow the team's guidlines.

##ETA - 24 hours

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

I will create a dedicated page should be created to display product details instead of using a modal. This involves creating a new product folder within the app directory and developing a static page that includes the same details currently displayed in the modal, excluding the close button. The page should be designed to be visually appealing and consistent with the rest of the application while ensuring full responsiveness across different screen sizes. This approach will enhance the user experience by providing a more spacious and navigable interface for viewing extensive product information.

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

I will create a new product folder in the app directory and implement a dedicated product page that displays static details for a single product. The layout will ensure it is visually appealing and fully responsive, maintaining consistency with the rest of the application. The close button will be removed, as it is unnecessary for this page.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by MarcusDavidG** [comment]
Can I take this from here?

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world.
### How would I approach this issue?
First, I'll start by analizing how are current components structured to make sure the new ones stay consistent with the already implemented patterns.
After that I'll start creating the smallest dynamic/reusable components that I would need for this page. Once all this smaller components are implemented, I'll continue with the product page as its own component, always ensuring that both the small components and the page itself remains responsive on all devices.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.


How will I tackle this task?

To address the issue, I'll build a product page in a new folder under the app directory, showcasing the same product details currently in the modal but in a cleaner, more accessible layout. I'll ensure the design is responsive and visually aligned with the rest of the app.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by MildPXL** [comment]
Hi! I’m a skilled product designer and front-end developer passionate about creating user-centered, scalable, and responsive designs. My background includes working on SaaS platforms, blockchain applications, and responsive web components, with achievements such as being a Web3 hackathon finalist and a top performer in the HNGx internship.
Here’s my portfolio: [https://precious.super.site/].

Approach to the Task

Reimagine the User Experience:

While modals are great for quick interactions, a dedicated product page provides the space needed for users to explore product details comfortably.
I will design the page to maintain consistency with the app’s overall style while offering an uncluttered, structured layout for better readability and usability.
I'd Build a product page that includes all the current modal details but excludes the close button, ensuring a full-page layout optimized for detailed information. Then use grids or flexible layouts to structure the content logically, making it easy for users to navigate.

I’ll also use the app’s existing design system to ensure the product page aligns with the application's aesthetic.
Add visual elements, such as high-quality images and typographic hierarchy, to enhance the presentation of product details. I'd also ensure the page will be fully responsive, adapting gracefully to all screen sizes, from desktops to mobile devices.

**Comment by RareMmemshima** [comment]
Could I try solving this?
i'm a frontend and smart contract developer. I have a solid background with react, tailwind, nextjs, javascript, typescript, cairo ETC.  
I will implement this task as expected. 
I'm new to onlydust and i look forward to contributing to this project.
