### ISSUE TITLE
Design Pagination and Results Selector

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#57]
## 📘 **Description**

A pagination layout is essential to enhance user experience in the Marketplace by dividing product listings into manageable sections. This visual structure prevents overwhelming users with a continuous scroll of items, instead allowing them to navigate through pages. Additionally, a selector to customize the number of items displayed per page improves flexibility. Although the pagination won't be functional yet, designing it now aligns the interface with future usability goals and ensures consistency in the Marketplace layout.

## 🔢 **Steps**

1. Create a new file named `products-pagination.tsx` inside the `components/marketplace` directory. If the directory does not exist, create it.
2. Name the component ProductsPagination.
3. Implement the pagination and selector layout using **shadcn/ui** components:
    - [Pagination](https://ui.shadcn.com/docs/components/pagination)
    - [Select](https://ui.shadcn.com/docs/components/select)
4. Ensure the layout is responsive and integrates seamlessly with the Marketplace design.

## ✅ **Acceptance Criteria**

- Include a pagination component.
- Include a results selector with options to display 10, 20, 30, and 50 items per page.
- The design should be responsive.

## 🌎 **References**

- Reference attached images for design inspiration, but the final implementation does not need to be identical.

![image (11)](https://github.com/user-attachments/assets/de9045c3-f6ec-41e7-85d9-4d5abca273df)

![image (12)](https://github.com/user-attachments/assets/26910cc6-b82c-42aa-8e8f-88a25133b89f)

## 📜 **Additional Notes**

- Focus solely on the visual implementation; functionality is not required at this stage.

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by armandocodecr** [comment]
### **Issue Submission: Implementing a Responsive Pagination Layout for Marketplace**

**Hi Daniel,**

I’m excited to contribute to improving the user experience in the Marketplace. After thoroughly reviewing the issue description and guidelines, I propose the following approach to implement the pagination layout and the results selector. My goal is to create a solution that not only aligns with the Marketplace design but also sets a solid foundation for future functionality.

### **Proposed Solution**

**1. File and Component Structure**

I will create a new file named products-pagination.tsx inside the components/marketplace directory. The component will be named ProductsPagination to maintain clarity and consistency.

**2. Design Implementation**

•	**Pagination Component:**

I will use the Pagination component from shadcn/ui to ensure the layout is clean, modern, and consistent with the rest of the UI. The pagination controls will be intuitive, providing clear navigation between pages.

•	**Results Selector:**

I will incorporate a Select component from shadcn/ui to offer users the flexibility to display 10, 20, 30, or 50 items per page. The selector will be positioned adjacent to the pagination controls for seamless interaction.

**3. Responsive Design**

I will ensure the layout is fully responsive by leveraging TailwindCSS, allowing the component to adapt smoothly to various screen sizes and devices. The design will integrate naturally with the existing Marketplace structure.

### **Design Considerations**

•	The visual design will be inspired by the reference images provided, ensuring consistency with the Marketplace’s aesthetics while keeping the interface intuitive and user-friendly.

•	While functionality is not required at this stage, I will structure the code to facilitate easy integration of logic in future iterations.

### **Why This Approach?**

1.	**Consistency:** Leveraging shadcn/ui components ensures the design aligns with the overall UI library, maintaining a cohesive look and feel.

2.	**Scalability:** The proposed structure is easily extendable, making it straightforward to add functionality later.

3.	**Experience:** I have prior experience implementing responsive components and pagination in various projects, ensuring a polished and reliable solution.

4.	**Efficiency:** The clean and modular approach will keep the codebase maintainable, aligning with best practices.

**Comment by Ayoazeez26** [comment]
I will create the `products-pagination.tsx` file inside the components/marketplace directory after checking for the directory and creating it if it doesn't exist. The name of the component will be ProductsPagination.
I will use shadcn/ui components to implement both the pagination and selector. I will make sure the layout is responsive and matches the marketplace design. Before submitting a PR I will make sure the design is fully responsive and the selector options would be 10, 20, 30, 40 and 50 items per page.
ETA - 1 day

**Comment by mimisavage** [comment]
Is it okay if I tackle this?

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, I have been contributing to this project and would like to keep doing so I would like to contribute to this issue!
I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 

Id follow the instructions mentioned in the issue, I’d create the new file called products-pagination.tsx inside the components/marketplace folder. I’d name the component ProductsPagination and use shadcn/ui components for the pagination and selector, ensuring they look good on any screen size and match the Marketplace design.

**Comment by Supa-mega** [comment]
Can I try solving this issue?

**Comment by BigBen-7** [comment]
i would love to work this issue?

**Comment by khayss** [comment]
Can I start working on this?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by AdejareSamad** [comment]
Hi @danielcdz , I'd love to work on this design.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by abdegenius** [comment]
Could I grab this task?

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by martinvibes** [comment]
I'd like to handle this task.

**Comment by Naomi-Gift** [comment]
May I try my hand at this?

**Comment by ShantelPeters** [comment]
Would love to tackle this!

**Comment by jesusre890** [comment]
My portfolio: https://jesus-nine.vercel.app/

**Comment by Levi-Ojukwu** [comment]
## About Me 
Hello  @danielcdz, I'm Levi
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## Tackling this issue
- To tackle this issue, first i will create a directory named `Marketplace` where the `products_pagination.tsx` page will be.
- Then I will create the `products_pagination.tsx` file inside the `Marketplace` directory that was created in the `Component`.
- Then I will write a  logic that implemets the pagination and the selector layout.
- I will use shadcn/ui component, making it simple to maintain a consistent look and feel across your application.

If assigned the task, I will ensure compliance with the team's guideline.

## ETA - 10 -12 hours max

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

1. I will create a ProductsPagination component inside the components/marketplace directory.
2.  It will use shadcn/ui components for pagination and a results selector to display 10, 20, 30, or 50 items per page. 
3. The layout will be responsive and integrate seamlessly with the Marketplace design.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by MildPXL** [comment]
Hi, I'm a product designer who has worked on variety of projects with a pagination requirement.

You can view some of them here: https://www.figma.com/design/8LwReCqiZXDYzSoBK3uGAq/pagination?node-id=0-1&t=3eKNPcEApC6w8jp8-1

I'd love to be assigned to this!
