### ISSUE TITLE
Remove the Connect Wallet button in hero section

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#58]
## 📘 Description

The "Connect Wallet" button in the Hero section on the Landing Page should be removed, as it has now been moved to the header for better navigation and visibility.

## 🔢 Steps

1. Remove the "Connect Wallet" button from the Hero section.
2. Reposition the "Explore Marketplace" button for better alignment and design.
3. Ensure the "Explore Marketplace" button is responsive.

## ✅ Acceptance Criteria

- The "Connect Wallet" button has been removed from the Hero section.
- The "Explore Marketplace" button is properly aligned and visually appealing.
- The button is responsive.

## 🌎 References

Not applicable

## 📜 Additional Notes

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by BigBen-7** [comment]
Can this be assigned to me??

**Comment by 0xdevcollins** [comment]
I'd like to handle this task.

**Comment by jaykayudo** [comment]
@danielcdz  Can i be assigned this issue?

I am a full stack software developer with ample experience in building innovative and scalable solutions. 

## How i will tackle this?
- I will follow the contribution guideline accurately to ensure that the project works properly locally and i open a good PR
- I will remove the connect button from the hero section
- I will make sure "Explore Marketplace" button is properly aligned and visually appealing
- I will open a PR within 2 days

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by josephchimebuka** [comment]
May I take care of this?

**Comment by Supa-mega** [comment]
Could I be assigned to this?

**Comment by khayss** [comment]
Can I take care of this issue?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Judah04** [comment]
Hi @danielcdz, I'd love to work on this task.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Steph3097** [comment]
Hello! Im Sttef
I’d love to help you on this issue! I'm part of dojo coding  With my experience in front-end development, I enjoy working on tasks like  making interfaces cleaner and easier for users to navigate.
Here’s the approach:
- Remove the "Connect Wallet" Button
- Reposition the "Explore Marketplace" Button
- Make It Responsive
- Check everything looks good
 I’m excited to help bring this improvement to life!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by OWK50GA** [comment]
Could I grab this task?
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

My approach:
I would go to the component rendering the Hero section and find the connect Wallet button. I would then remove the button. 
I will make sure there's no after effect, by making sure the alignment of the "Explore Marketplace" button stays right and is responsive after my change 


Expect my first PR within

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by Kingsuite** [comment]
Could I take on this issue?

**Comment by caxtonacollins** [comment]
I’d love to work on this task.

**Comment by abdegenius** [comment]
May I take care of this?

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by ONEONUORA** [comment]
Could I try solving this? I am a full stack and blockchain developer. ETA 24 hours

**Comment by 0xDeon** [comment]
Let me try this one!

I’ll solve this by removing the "Connect Wallet" button from the Hero section and adjust the layout to center and align the "Explore Marketplace" button. I’ll ensure it remains responsive across all screen sizes too.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by akintewe** [comment]
Hello I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript. I’ve made over 14 contributions to over 9 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.
I can handle this task.
ETA is 21hours.

**Comment by Luluameh** [comment]
Hi, I’m a frontend developer with experience in TypeScript and responsive design. I’ve reviewed the requirements for removing the "Connect Wallet" button and repositioning the "Explore Marketplace" button in the Hero section, and I’m confident I can implement the necessary changes.

Plan to Solve the Issue:

Remove "Connect Wallet" Button:

Remove the "Connect Wallet" button from the Hero section on the Landing Page.
Ensure that no unnecessary styles or dependencies are left behind after removal.
Reposition "Explore Marketplace" Button:

Move the "Explore Marketplace" button to a more visually appealing and aligned position.
Adjust the layout to maintain a clean and consistent design.
Ensure Responsiveness:

Test and ensure that the "Explore Marketplace" button remains responsive on different screen sizes.
Adjust the layout and button size as necessary for both mobile and desktop views.
Testing and Validation:

Verify that the "Connect Wallet" button has been completely removed and that the "Explore Marketplace" button is aligned correctly.
Ensure there are no visual regressions or layout shifts after making the changes.
Estimated Completion Time: 1 day

**Comment by ShantelPeters** [comment]
Could I take a shot at this?

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

First, I’d go to the Hero section on the Landing Page and find the code where the "Connect Wallet" button is located. I’d remove that button from the section. Next, I’d check the "Explore Marketplace" button and reposition it to make sure it aligns properly with the rest of the layout. I’d also ensure that the "Explore Marketplace" button is responsive, so it looks good on all screen sizes. Finally, I’d test everything to make sure the design looks good and the button works as expected.

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

1. I will remove the "Connect Wallet" button from the Hero section and reposition the "Explore Marketplace" button for better alignment. 
2. I'll ensure the button remains visually appealing and responsive across different screen sizes.


Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

How will I tackle this task?

To address this, I will delete the "Connect Wallet" button from the Hero section and adjust the "Explore Marketplace" button for optimal alignment and design. The button will be fully responsive to maintain consistency with the rest of the layout.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by morelucks** [comment]
Gm , I am lucky and Id like to fix this issue, I am skilled at frontend frameworks like react, nextjs and tailwindcss. My ETA is 20mins.

**Comment by akintola4** [comment]
May I take this issue on?
