### ISSUE TITLE
Standardize ProductUploadModal Design

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#59]
## 📘 Description

The `ProductUploadModal` needs to adopt standardized **shadcn/ui** components for a consistent and responsive design. Additionally, the component will need to be renamed, and an element should be repositioned to improve organization and alignment with the overall style. These changes will help maintain a unified user interface and improve the code structure.

## 🔢 Steps

1. Replace the current elements in `ProductUploadModal` with **shadcn/ui** components.
2. Rename the component to `AddProductModal`.
3. Center the modal's title.
4. Rename the file to `add-product-modal.tsx`.
5. Move the file to the `components/marketplace` folder, creating the folder if it does not already exist.

## ✅ Acceptance Criteria

- The modal uses the **shadcn/ui** components.
- The component has been renamed to `AddProductModal`.
- The modal's title is centered.
- The file has been renamed and moved correctly.
- The modal design is responsive.

## 🌎 References

- [Input](https://ui.shadcn.com/docs/components/input)
- [Label](https://ui.shadcn.com/docs/components/label)
- [Select](https://ui.shadcn.com/docs/components/select)
- [Textarea](https://ui.shadcn.com/docs/components/textarea)

## 📜 Additional Notes

- The form does not need to be functional at this stage; focus on design only.

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by BigBen-7** [comment]
i would like for this to be assigned to me

**Comment by mimisavage** [comment]
May I take this issue on?

**Comment by Supa-mega** [comment]
May I be assigned to this?

**Comment by khayss** [comment]
I’d like to work on this.

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Yunusabdul38** [comment]
Can I jump on this task?

**Comment by Judah04** [comment]
Hi @danielcdz, I'd love to work on this task.

**Comment by zintarh** [comment]
I'd like to handle this task.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by Tzienom** [comment]
Hi. I would love to work on this issue.

**Comment by 0xDeon** [comment]
Let me try this one!

I'll start by creating a dedicated product page by first establishing a new route in the Next application, designing a layout that expands on the current modal's content. My implementation will focus on translating modal content into a full-page view that provides a more detailed and user-friendly product information experience.

**Comment by Tzienom** [comment]
Hi. I would love to work on this issue.

**Comment by abdegenius** [comment]
Can I contribute to this one?

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by jahrulezfrancis** [comment]
I noticed that the ProductUploadModal needs some updates to make it fit better with the overall design. I’ll go ahead and:

Replace the current elements with shadcn/ui components for consistency.
Rename the component to AddProductModal and the file to add-product-modal.tsx.
Center the title in the modal.
Move the file to the components/marketplace folder (and create it if needed).
I’ll focus on getting the design right and making sure it’s responsive. Functionality isn’t needed right now, so I’ll stick to improving the layout and structure. 
I can have this done within 24 hours

**Comment by johnnyzaet08** [comment]
Hi friend ⛩️⛩️, I would love to work on this assignment.

I have previously worked with several projects in React, Tailwind CSS, TypeScript, etc. I have experience in this kind of tasks.

**Comment by ShantelPeters** [comment]
Is this issue still available?

**Comment by MarcusDavidG** [comment]
Can I tackle this one?

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

1. To standardize the design, I'll replace the current elements in the ProductUploadModal with shadcn/ui components. 
2. I'll rename the modal to AddProductModal, center the title, and ensure it’s placed in the appropriate folder while maintaining a responsive design.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

How will I tackle this task?

- I will refactor the ProductUploadModal by using shadcn/ui components for consistency and responsiveness.
-  The modal will be renamed to AddProductModal, with its title centered and the file moved to the correct folder.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by salazarsebas** [comment]
Hi @danielcdz,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Rename the component.
- Align the style for better organization.
- Component replacement.
- Use the references to make the requested ones.
- Perform all tests and send the pr waiting for feedback.
