### ISSUE TITLE
Remove More Details Button & Make Image/Title Clickable

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#62]
## 📘 Description

The "More Details" button on the product card should be removed. Instead, both the product image and title should be clickable and redirect to a static Product Page. This will reduce the number of buttons on the card and simplify the design, improving the user experience.

## 🔢 Steps

1. Remove the "More Details" button from the product card.
2. Make the product image clickable and redirect to the static Product Page.
3. Make the product title clickable and redirect to the static Product Page.

## ✅ Acceptance Criteria

- The "More Details" button is removed from the product card.
- The product image and title are clickable and correctly redirect to the static Product Page.
- The design is clean, intuitive, and responsive.

## 🌎 References

- Not applicable.

## 📜 Additional Notes

- The Product Page should be static for now, with all cards linking to this page.
- Blocked by: #56 and #55 

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by BigBen-7** [comment]
can i solve this issue?

**Comment by mimisavage** [comment]
Can I start working on this?

**Comment by josephchimebuka** [comment]
Is it okay if I tackle this?

**Comment by Kingsuite** [comment]
Is it okay if I tackle this? ETA 24hrs

**Comment by khayss** [comment]
Can I try solving this issue?

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Supa-mega** [comment]
Is this issue still available?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by OWK50GA** [comment]
Let me try this one!
Let me be assigned once #55 and #56 are solved, so that I can contribute to this project

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by starknetbrother** [comment]
Can I take this issue?

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by abdegenius** [comment]
Can I jump on this task?

**Comment by austineblaise** [comment]
**How I can solve the issue**

I will remove the "More Details" button from the product card and make both the product image and title clickable, redirecting to the static Product Page. This will simplify the design, improve user experience, and ensure the page is clean, intuitive, and responsive.

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by ONEONUORA** [comment]
May I pick this up? I am a full stack and blockchain developer. ETA 24 hours

**Comment by Emmanex01** [comment]
Would love to tackle this!

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Luluameh** [comment]
Could I take over this issue?

**Comment by ShantelPeters** [comment]
Can I start working on this?

**Comment by Gladchux14** [comment]
hello! my name is Gladchux14.
I have extensively used JavaScript and typescript to deliver quality and responsive interactive projects.

 i have worked on Ecommerce sites, you can check out my GitHub: https://github.com/Gladchux14.

My plan to resolve this issue:
create a branch after cloning the repository.
Study the codebase to understand it.
locate the product page.
remove the more details button.
include links to the image and tittle and add an event functionality to them.
implement styling from the design.
ensure responsiveness for all screen sizes.
raise an explicit PR and notify maintainers.

my ETA for this would be 24 hrs.

**Comment by MarcusDavidG** [comment]
I'd love to give this a go.

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:
1. I will remove the "More Details" button from the product card and make both the product image and title clickable.
2.  Clicking either will redirect the user to the static Product Page, improving the design and simplifying navigation.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

How will I tackle this task?
- To improve the user experience, I will remove the "More Details" button and make the product image and title clickable.
-  These elements will redirect to the static Product Page, streamlining the design and enhancing the flow.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by Nityam573** [comment]
I'd love to give this a go.

**Comment by Gladchux14** [comment]
I have created a draft PR , waiting on blockers. @derianrddev @danielcdz

**Comment by derianrddev** [comment]
@Gladchux14 The issue #55 has been merged. To avoid any further waiting, you can create a folder called `product` in `app` and inside it, a `page.tsx` file with any content. Redirect to that page.

Let us know if you need any help or clarification.

**Comment by derianrddev** [comment]
@Gladchux14 The issue #56 has also been merged.
