### ISSUE TITLE
Enhance Dark Mode Implementation

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#63]
## 📘 Description

- The current dark mode implementation works well but can be improved to simplify maintenance and provide a more customizable experience. By adopting the **shadcn/ui** approach, its components will automatically adjust to dark mode and allow users to choose between their personal preference or the system/browser setting.

## 🔢 Steps

1. Replace the current dark mode logic with the approach outlined in the official shadcn/ui documentation.
2. Ensure that the change is applied correctly in both light and dark modes, according to the user's selected preference.

## ✅ Acceptance Criteria

- The dark mode logic has been successfully replaced with the **shadcn/ui** approach.
- All components and pages work correctly in both light and dark modes according to the user's preference.

## 🌎 References

- [Official shadcn/ui dark mode documentation](https://ui.shadcn.com/docs/dark-mode/next)

## 📜 Additional Notes

- If the filters don’t display correctly in dark mode, don’t worry. These issues will be addressed in future improvements.
- Blocked by: #54 

⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by 0xdevcollins** [comment]
I’d like to work on this.

**Comment by BigBen-7** [comment]
i would love to solve this

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by khayss** [comment]
Let me try this one!

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by SYLVIANNORUKA** [comment]
Could I grab this task?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by Steph3097** [comment]
Hi! Im Sttef!
I’m excited to work on this issue. I have over five years of experience in front-end working with react, MUI, tailwind, etc
Here’s how I’d approach the issue:
- I’ll follow the official shadcn/ui documentation to replace the current dark mode logic.
-I’ll test the feature to ensure it works correctly in both modes, respecting the user’s choice.
Thanks for considering my application!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by caxtonacollins** [comment]
Is it okay if I tackle this? this will be my first time contributing.

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

To improve the dark mode implementation, I would replace the existing logic with the approach recommended in the shadcn/ui documentation. This will allow components to automatically adjust to dark mode based on the user's preference or system setting. I will verify that all components and pages function correctly in both light and dark modes, ensuring a smooth and customizable user experience.

**Comment by abdegenius** [comment]
I’d like to help with this.

**Comment by AnoukRImola** [comment]
Hello @danielcdz!

I would like to work on this issue; I have experience with this type of implementation. You can check how I handled dark mode integration in previous projects at this [Link](https://github.com/safetrustcr/Frontend/commit/227cd7d3b3693e79e32dbb06ded082f6a712b07b)

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by ONEONUORA** [comment]
May I be assigned to this? I am a full stack and blockchain developer. ETA 24 hours

**Comment by 0xDeon** [comment]
Mind if I take this issue?

I’ll start by replacing the existing dark mode logic with the shadcn/ui approach, ensuring components automatically adapt to user preferences or system/browser settings. I’ll test all components and pages to confirm they function correctly in both light and dark modes.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by wheval** [comment]
Hello, Can I take care of this issue?
I'm Wheval an experienced Frontend Developer.
I have multiple experience working with Shadcn/ui. This should be really straightforward.
I would ensure to test that Dark mode works properly on all pages.

ETA is 1 day.

**Comment by ShantelPeters** [comment]
May I try my hand at this?

**Comment by brolag** [comment]
I'd like to work on this issue. I started the front end boilerplate for the project so I might be able to tackle this faster. 

My plan is to check if there's a general dark-theme implementation first then implement it or make it easy to maintain.

**Comment by MarcusDavidG** [comment]
Could I take on this issue?

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz, I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

1. I will replace the current dark mode implementation with the shadcn/ui approach as outlined in the official documentation.
2. This will ensure that all components automatically adjust to light or dark mode based on the user's preference or system settings.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

How will I tackle this task?

- To enhance dark mode, I will adopt the shadcn/ui method for a more flexible and maintainable solution. 
- The new implementation will respect both the system/browser setting and user preferences, ensuring seamless theme switching across components.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to various projects like Chainevents and Arkprojects etc .
Please assign this issue to me.

Thank you!
