### ISSUE TITLE
Add Delivery Location Button

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/SafeSwap#64]
## 📘 Description

A button should be added to the header allowing users to select the delivery country. Initially, the only available country will be **Costa Rica**, which will be displayed in a select within a modal. This button should be accompanied by an icon and allow users to view the selected country. When the button is clicked, a modal will open with a **select** component from **shadcn/ui** displaying the option for **Costa Rica** along with its flag. The modal can also contain any other information you deem relevant. The design will be **responsive** to ensure proper functionality across different devices.

## ✅ Acceptance Criteria

- The **"Deliver to Costa Rica"** button is located in the header and contains an icon.
- When clicked, the button opens a modal with a select showing only **Costa Rica** with its flag.
- The select is based on the **shadcn/ui** component.
- The design is **responsive**.

## 🌎 References

- [Lucide React Icons](https://lucide.dev/icons/)
- [shadcn/ui Select Component](https://ui.shadcn.com/docs/components/select)

## 📜 Additional Notes
- Blocked by: #54 

⚠ Do not apply until the ODHack begins.

⚠ Read our guidelines before applying.

**Comment by sonkiee** [comment]
can i take this

**Comment by 0xdevcollins** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
I'd love to work on this!

**Comment by josephchimebuka** [comment]
Could I take a shot at this?

**Comment by khayss** [comment]
I’d like to resolve this.

I am a fullstack developer. I can work on frontend applications using  ReactJS, NextJS, TypeScript, TailwindCSS and vanilla CSS.

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi(@deeseeker), a frontend developer with over two years of experience in React,TS and JS. 

I have experience using shadcn ui , creating responsive and I can submit a PR in the next few hours. Please, allow me take this issue.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by aurlic** [comment]
Hey I would love to give this issue a go. I've had the occasion to work on the Front End of a project before and would really like to perfect my skills with this issue. Thanks in advance !

**Comment by SudiptaPaul-31** [comment]
I’d like to resolve this.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
will be glad to work on this as my first contribution to this project
I have solid experience with contract integration and have worked on multiple web3 projects (open source and personal projects

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Michaelkingsdev** [comment]
I would love to tackle this issue. My ETA is 3 days. Thanks

**Comment by Tzienom** [comment]
Hi. I would love to work on this issue.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by caxtonacollins** [comment]
I will love to start working on this. Please assign me.

**Comment by abdegenius** [comment]
Let me handle this issue!

**Comment by abdegenius** [comment]
Let me handle this issue!

**Comment by Ndifreke000** [comment]
Could I try solving this?

**Comment by therealemino** [comment]
Hi, Can I handle this.

**Comment by AdejareSamad** [comment]
Can I handle this task?

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by building the "Deliver to Costa Rica" button to be responsive and I will use shadcn/ui. ETA 2 days

**Comment by ONEONUORA** [comment]
May I try my hand at this? I am a full stack and blockchain developer. ETA 24 hours

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will add a "Deliver to Costa Rica" button with an icon in the header. When clicked, it will open a responsive modal with a shadcn/ui select component displaying Costa Rica and its flag. The design will ensure functionality and consistency across devices.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by jesusre890** [comment]
Proposal for Issue: Delivery Country Selection Button
Key Features:
Header Button:

Displays "Deliver to Costa Rica" with an icon using Lucide React Icons.
Shows the selected country ("Costa Rica") by default.
Opens a modal when clicked.
Modal:

Contains a shadcn/ui Select component with "Costa Rica" as the only option, accompanied by its flag.
Allows space for additional future information if needed.
Responsiveness:

Ensures the button and modal work across all device sizes (mobile, tablet, desktop).

My portfolio: https://jesus-nine.vercel.app/

**Comment by ShantelPeters** [comment]
Could I take on this issue?

**Comment by PedroCo3lho** [comment]
Can I take this issue?

**Comment by Jemiiah** [comment]
1. Button in Header:
Add a button in the header that contains an icon. This can be achieved using HTML and CSS. 
2. Modal Implementation:
When the button is clicked, a modal will open. The modal should contain a select component that allows users to choose Costa Rica as the delivery country. This can be implemented using the `shadcn/ui` select component
3. JavaScript Functionality:
Use JavaScript to open and close the modal and to manage the selection
4. Styling for Responsiveness:
Ensure that the modal and select component are styled for responsiveness. This can be done by setting appropriate CSS media queries

**Comment by Jagadeeshftw** [comment]
Hello @danielcdz , I’d love to work on this issue as I have strong experience with front-end development. 

My Approach:

1. I’ll add a "Deliver to Costa Rica" button in the header, using an icon from Lucide React. 
2. When clicked, the button will open a modal containing a select component from shadcn/ui, where users can choose Costa Rica as the delivery country, accompanied by its flag.

Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi @danielcdz , I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

How will I tackle this task?

- I plan to implement a "Deliver to Costa Rica" button in the header, which will trigger a modal on click. 
- The modal will feature a select dropdown, displaying only Costa Rica with its flag, using the shadcn/ui select component for a clean and responsive design.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  

Looking forward to contributing!
